SELECT EMPNO, ENAME, SAL FROM EMP e ;

SELECT ALL JOB FROM EMP e;

SELECT DISTINCT DEPTNO,JOB NO FROM EMP e ;

SELECT 10*10 FROM dual;

SELECT * FROM EMP e ;

SELECT EMPNO, ENAME, SAL, SAL * 12  FROM EMP;