SELECT * FROM EMP WHERE SAL >2000
INTERSECT 
SELECT * FROM EMP WHERE SAL<2900 ;

SELECT SYSDATE-1 어제 , SYSDATE 오늘 ,SYSDATE+1 내일, SYSDATE - SYSDATE 차이 FROM DUAL;

SELECT * FROM EMP ;  

SELECT EMPNO, ENAME, HIREDATE, SYSDATE - HIREDATE 경력 FROM EMP;

SELECT EMPNO, ENAME, HIREDATE-SYSDATE , MONTHS_BETWEEN(SYSDATE, HIREDATE) 경력 
FRO1M EMP; 