CREATE TABLE EMP_FK(
 EMPNO NUMBER(4,0) PRIMARY KEY,
 ENAME VARCHAR2(10) NOT NULL,
 JOB VARCHAR2(9) NOT NULL,
 MGR NUMBER(4),
 HIREDATE DATE,
 SAL NUMBER(7,2),
 COMM NUMBER(7,2),
 DEPTNO NUMBER(2) REFERENCES DEPT (DEPTNO)
);