SELECT EMPNO,ENAME, (SELECT dname FROM DEPT d WHERE d.deptno=e.deptno) FROM EMP e ;

SELECT * FROM emp WHERE SAL > (SELECT AVG(sal) FROM emp WHERE DEPTNO=20);
SELECT MIN(sal) FROM emp WHERE DEPTNO=30;
SELECT * FROM emp WHERE SAL < (SELECT MIN(SAL) FROM emp WHERE deptno);
SELECT * FROM EMP e WHERE SAL < ALL (SELECT sal from emp WHERE DEPTNO=30);
SELECT sal FROM EMP e WHERE DEPTNO = 30 ORDER  BY SAL DESC ;
SELECT * FROM EMP e WHERE EXISTS(SELECT * FROM DEPT d WHERE DEPTNO=40);	