SELECT * FROM EMP WHERE JOB LIKE 'SALESMAN';	

SELECT * FROM EMP e 
SELECT * FROM 
SELECT * FROM E

SELECT NULL +100 FROM DUAL;
SELECT NULL +100 FROM DUAL;

SELECT EMPNO,ENAME,SAL,SAL * 12+ COMM 연봉 FROM EMP;

SELECT * FROM EMP WHERE COMM IS NOT NULL ;

SELECT * FROM EMP WHERE SAL<2900 ORDER BY SAL ; 