SELECT EMPNO,ENAME, (SELECT dname FROM DEPT d WHERE d.deptno=e.deptno) FROM EMP e ;

SELECT * FROM emp WHERE SAL > (SELECT AVG(sal) FROM emp WHERE DEPTNO=20);
SELECT MIN(sal) FROM emp WHERE DEPTNO=30;
SELECT * FROM emp WHERE SAL < (SELECT MIN(SAL) FROM emp WHERE deptno);
SELECT * FROM EMP e WHERE SAL < ALL (SELECT sal from emp WHERE DEPTNO=30);
SELECT sal FROM EMP e WHERE DEPTNO = 30 ORDER  BY SAL DESC ;
SELECT * FROM EMP e WHERE EXISTS(SELECT * FROM DEPT d WHERE DEPTNO=40);	 
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT d ;
SELECT * FROM emp WHERE sal IN (SELECT MAX(SAL) FROM emp GROUP BY DEPTNO);
SELECT * FROM (SELECT empno,ename,job FROM EMP e WHERE deptno IN (10,20)) E;
SELECT * FROM (SELECT empno,ename,job FROM EMP e WHERE e.job IN ('SAELSMAN','MANAGER')) E;
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC) VALUES(50,'DATABASE','INCHEON');
SELECT * FROM DEPT_TEMP;
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP ;
INSERT INTO DEPT_TEMP VALUES (60,'WEB','INCHEON');
INSERT INTO DEPT_TEMP VALUES (70,'MOBILE',NULL);
INSERT INTO DEPT_TEMP VALUES (70,'MOBILE','');
INSERT INTO DEPT_TEMP (DNAME,DEPTNO) VALUES ('AI',80);
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,HIREDATE) VALUES (9999,'이이름','CLERK',SYSDATE);
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,HIREDATE) VALUES (9998,'김이름','CLERK','2024-10-02');
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,HIREDATE) VALUES (9997,'최이름','CLERK','2024/10/02');

UPDATE DEPT_TEMP SET LOC = 'SEOUL';
SELECT * FROM EMP_TEMP;

SELECT * FROM DEPT_TEMP;

DELETE FROM DEPT_TEMP WHERE DEPTNO=70;
COMMIT;

UPDATE DEPT_TEMP SET LOC='SEOUL' WHERE DEPTNO =60;


CREATE TABLE MEMBER(
EMAIL VARCHAR2(65),
PASSWORD VARCHAR2(65),
NAME VARCHAR2(45),
AGE NUMBER(3),
INTRO CLOB,
REG_DT DATE
);

ALTER TABLE MEMBER ADD MOBILE VARCHAR2(15);
ALTER TABLE MEMBER RENAME COLUMN MOBILE TO CELLPHONE;













RENAME MEMBER TO USER_INFO;


TRUNCATE TABLE DEPT_TEMP;

	SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME='EMP';
	DROP TABLE USER_INFO;
	
CREATE TABLE MEMBER(
EMAIL VARCHAR2(65) NOT NULL,
PASSWORD VARCHAR2(65) NOT NULL,
NAME VARCHAR2(45) NOT NULL,
AGE NUMBER(3),
REG_DT DATE
);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MEMBER';

INSERT INTO MEMBER VALUES('USER01@TEST.ORG','123456','사용자01',NULL,SYSDATE);
DROP TABLE MEMBER;
	
CREATE TABLE MEMBER(
EMAIL VARCHAR2(65) UNIQUE,
PASSWORD VARCHAR2(65) NOT NULL,
NAME VARCHAR2(45) NOT NULL,
REG_DT DATE
);
INSERT INTO MEMBER VALUES(NULL,'123456','사용자01',SYSDATE);
SELECT * FROM MEMBER;
























SELECT *FROM emp_constraintns WHERE TABLE_name ='EMP';



