SELECT ENAME,UPPER(LOWER(ENAME)) ,INITCAP(LOWER(ENAME)) 
FROM EMP; -- 단일행 함수
SELECT SUM(SAL) FROM EMP; -- 다중행 함수
SELECT * FROM  EMP;

SELECT LENGTH('안녕하세요') "문자 개수" , 
	LENGTHB('안녕하세요') "바이트 수"
FROM DUAL;

SELECT ENAME,SUBSTR(ENAME,2,3), SUBSTR(ENAME,2) FROM EMP ;

SELECT ENAME, INSTR(ENAME, 'S') FROM EMP;

-- 이름에 S가 포함된 직원 목록 ENAME LIKE '%S%'

SELECT * FROM EMP e  WHERE INSTR(ENAME,'S') >0;
 
SELECT REPLACE('010-3481-2101','-','') FROM DUAL;

SELECT LPAD('10',5,'0') FROM DUAL; 

SELECT RPAD(SUBSTR('010-3481-2101',1,9),LENGTH ('010-3481-2101'),'*')
FROM DUAL;

SELECT EMPNO, ENAME, JOB, CONCAT(CONCAT(CONCAT(EMPNO,':'),CONCAT( ENAME,':')), JOB)"직원명:직책" 
FROM EMP;
SELECT EMPNO, ENAME, JOB, 
EMPNO||':'||ENAME||':'||JOB "사원번호:직원명:직책" FROM EMP;

SELECT  TRIM(BOTH'_' FROM '          A________')||'B' FROM DUAL;
SELECT LTRIM('         A          ')||'B' FROM DUAL;
SELECT 
ROUND(10.567) 반올림,
CEIL(10.2)올림,
FLOOR(10.567) 버림,
TRUNC(10.5678,2)절사,
MOD (10,3) 나머지
FROM DUAL;

SELECT ADD_MONTHS(TO_DATE('10-02-2024','MM-DD-YYYY'),+3) FROM DUAL;

SELECT EMPNO,ENAME, TO_CHAR(HIREDATE, 'YYYY/MM/DD') HIREDATE, 
TO_CHAR(SAL,'9,999.99') SAL 
FROM EMP; 

SELECT EMPNO, ENAME, COMM, NVL2(COMM,'O','X') "O/X" FROM EMP;

SELECT EMPNO,ENAME, JOB,SAL,
DECODE(JOB,
'MANAGER',SAL*1.1,
'SALESMAN',SAL*1,05,
'ALALYST', SAL,
SAL*1.03) "인상 급여" 
FROM EMP;

SELECT EMPNO,ENAME, JOB,SAL,
CASE JOB WHEN'MANAGER'THEN SAL*1.1
 WHEN'SALESMAN'THEN SAL*1.05
 WHEN'ALALYST'THEN SAL
ELSE SAL*1.03
END "인상 급여"
FROM EMP;


SELECT EMPNO,ENAME,SAL,
CASE 
	WHEN SAL <=1500 THEN 'LOW'
WHEN SAL<=2500 THEN 'MID'
ELSE 'HIGH'
END "급여 수준"
FROM EMP;

SELECT SUM(SAL) 합,
		ROUND(AVG(SAL)) 평균,
		MAX(SAL) 최대,
		MIN(SAL) 최소
		FROM  EMP GROUP BY DEPTNO;
		
	SELECT COUNT(COMM) "수당 받는 직원수",
	COUNT(*) "전체 직원수" FROM EMP; 
	
SELECT DEPTNO, JOB, SUM(SAL) 합,
		ROUND(AVG(SAL)) 평균,
		MAX(SAL) 최대,
		MIN(SAL) 최소 FROM EMP GROUP BY DEPTNO, JOB ;
		

SELECT DEPTNO, JOB, SAL, ROUND(AVG(SAL)) "급여 평균" FROM EMP 
GROUP BY DEPTNO,JOB,SAL
HAVING ROUND(AVG(SAL))>=2000;

