SELECT EMPNO, ENAME, SAL FROM EMP e ;

SELECT ALL JOB FROM EMP e;

SELECT DISTINCT DEPTNO,JOB NO FROM EMP e ;

SELECT 10*10 FROM dual;

SELECT * FROM EMP e ;

SELECT EMPNO 사번, ENAME 이름, SAL 급여, SAL * 12 연봉  FROM EMP ORDER BY EMPNO ASC ;
SELECT EMPNO 사번, ENAME 이름, SAL 급여, SAL * 12 연봉  FROM EMP ORDER BY SAL DESC ;	



SELECT EMPNO, ENAME, job,SAL FROM EMP ORDER BY SAL DESC, EMPNO ASC ;
